#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += jd9365_dsi_vdo_holitech_hd720.o




KBUILD_CFLAGS += -Wno-error=unused-function -Wno-error=implicit-function-declaration
